resources:
- ../../base
namePrefix: dev-
patchesStrategicMerge:
- dev-configmap.yaml
- replica-count.yaml
configMapGenerator:
- literals:
  - TEXT1="Welcome to"
  - TEXT2="Devistan"
  name: rsvpconfig-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
